site_name: bobbyxdevel docs
site_description: 'Documentation about everything linux related!'
site_author: 'bobbyxdevel'
docs_dir: docs/
repo_name: 'bobbyxdevel/bobbyx-docs'
repo_url: 'https://github.com/bobbyxdevel/bobbyx-docs'
nav:
    - Home: index.md
    - Distributions & Distrohopping:
        - Introduction: distributions/intro.md
#        - Arch Linux: distributions/arch.md
#        - Ubuntu: distributions/ubuntu.md
#    - System Administration:
#        - Basics: system_administration/basics.md
#        - Advanced: system_administration/advanced.md
#    - Package Management: package_management.md
#    - Scripting & Automation:
#        - Bash: scripting_automation/bash.md
#        - Python: scripting_automation/python.md
    - Desktop Environments & Window Managers:
        - bspwm: desktop_environments/bspwm.md
#    - Kernel & Drivers: kernel_drivers.md
#    - Networking: networking.md
#    - Security & Hardening: security_hardening.md
#    - Filesystems & Storage: filesystems_storage.md
#    - Development & Productivity Tools: development_productivity.md
#    - BSD Corner: bsd_corner.md
    - Server: server/vps.md
theme:
  name: 'material'
  palette:
    scheme: 'slate'
