site_name: bobbyx docs
site_description: 'A docs test'
site_author: 'bobbyxdevel'
docs_dir: docs/
repo_name: 'bobbyxdevel/bobbyx-docs'
repo_url: 'https://github.com/mhausenblas/bobbyxdevel/bobbyx-docs'
nav:
    - Home: index.md
theme:
  name: 'material'
  palette:
    scheme: 'slate'